import { SchedulesService, SalonScheduleDto, ProfessionalScheduleDto, CreateBlockDto } from './schedules.service';
import { JwtPayload } from '../auth/jwt.strategy';
export declare class SchedulesController {
    private readonly schedulesService;
    constructor(schedulesService: SchedulesService);
    getSalonSchedule(user: JwtPayload): Promise<{
        id: string;
        createdAt: Date | null;
        updatedAt: Date | null;
        salonId: string;
        dayOfWeek: number;
        isOpen: boolean;
        openTime: string | null;
        closeTime: string | null;
    }[]>;
    updateSalonSchedule(user: JwtPayload, dayOfWeek: string, data: SalonScheduleDto): Promise<{
        id: string;
        createdAt: Date | null;
        updatedAt: Date | null;
        salonId: string;
        dayOfWeek: number;
        isOpen: boolean;
        openTime: string | null;
        closeTime: string | null;
    }>;
    getProfessionalSchedule(user: JwtPayload, professionalId: string): Promise<{
        id: string;
        createdAt: Date | null;
        updatedAt: Date | null;
        salonId: string;
        professionalId: string;
        startTime: string | null;
        endTime: string | null;
        dayOfWeek: number;
        isWorking: boolean;
    }[]>;
    getMySchedule(user: JwtPayload): Promise<{
        id: string;
        createdAt: Date | null;
        updatedAt: Date | null;
        salonId: string;
        professionalId: string;
        startTime: string | null;
        endTime: string | null;
        dayOfWeek: number;
        isWorking: boolean;
    }[]>;
    updateProfessionalSchedule(user: JwtPayload, professionalId: string, dayOfWeek: string, data: ProfessionalScheduleDto): Promise<{
        id: string;
        createdAt: Date | null;
        updatedAt: Date | null;
        salonId: string;
        professionalId: string;
        startTime: string | null;
        endTime: string | null;
        dayOfWeek: number;
        isWorking: boolean;
    }>;
    getProfessionalBlocks(user: JwtPayload, professionalId: string, startDate?: string, endDate?: string): Promise<{
        id: string;
        description: string | null;
        createdAt: Date;
        updatedAt: Date;
        salonId: string;
        status: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED";
        type: "OTHER" | "DAY_OFF" | "VACATION" | "SICK_LEAVE" | "PERSONAL" | "LUNCH" | "TRAINING" | "MAINTENANCE";
        professionalId: string;
        startTime: string | null;
        endTime: string | null;
        createdById: string;
        title: string;
        startDate: string;
        endDate: string;
        allDay: boolean;
        recurring: boolean;
        recurringPattern: "DAILY" | "WEEKLY" | "BIWEEKLY" | "MONTHLY" | null;
        recurringDays: unknown;
        recurringEndDate: string | null;
        requiresApproval: boolean;
        approvedById: string | null;
        approvedAt: Date | null;
        rejectionReason: string | null;
        externalSource: string | null;
        externalEventId: string | null;
    }[]>;
    getMyBlocks(user: JwtPayload, startDate?: string, endDate?: string): Promise<{
        id: string;
        description: string | null;
        createdAt: Date;
        updatedAt: Date;
        salonId: string;
        status: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED";
        type: "OTHER" | "DAY_OFF" | "VACATION" | "SICK_LEAVE" | "PERSONAL" | "LUNCH" | "TRAINING" | "MAINTENANCE";
        professionalId: string;
        startTime: string | null;
        endTime: string | null;
        createdById: string;
        title: string;
        startDate: string;
        endDate: string;
        allDay: boolean;
        recurring: boolean;
        recurringPattern: "DAILY" | "WEEKLY" | "BIWEEKLY" | "MONTHLY" | null;
        recurringDays: unknown;
        recurringEndDate: string | null;
        requiresApproval: boolean;
        approvedById: string | null;
        approvedAt: Date | null;
        rejectionReason: string | null;
        externalSource: string | null;
        externalEventId: string | null;
    }[]>;
    createProfessionalBlock(user: JwtPayload, professionalId: string, data: CreateBlockDto): Promise<{
        id: string;
        description: string | null;
        createdAt: Date;
        updatedAt: Date;
        salonId: string;
        status: "PENDING" | "CANCELLED" | "APPROVED" | "REJECTED";
        type: "OTHER" | "DAY_OFF" | "VACATION" | "SICK_LEAVE" | "PERSONAL" | "LUNCH" | "TRAINING" | "MAINTENANCE";
        professionalId: string;
        startTime: string | null;
        endTime: string | null;
        createdById: string;
        title: string;
        startDate: string;
        endDate: string;
        allDay: boolean;
        recurring: boolean;
        recurringPattern: "DAILY" | "WEEKLY" | "BIWEEKLY" | "MONTHLY" | null;
        recurringDays: unknown;
        recurringEndDate: string | null;
        requiresApproval: boolean;
        approvedById: string | null;
        approvedAt: Date | null;
        rejectionReason: string | null;
        externalSource: string | null;
        externalEventId: string | null;
    }>;
    deleteProfessionalBlock(blockId: string): Promise<void>;
    checkAvailability(salonId: string, professionalId: string, date: string, startTime: string, durationMinutes: string): Promise<import("./schedules.service").AvailabilityResult>;
}
//# sourceMappingURL=schedules.controller.d.ts.map