export { DashboardPage } from './DashboardPage';
export { ProductsPage } from './ProductsPage';
export { FinancePage } from './FinancePage';
export { ReportsPage } from './ReportsPage';
export { ClientsPage } from './ClientsPage';
export { AppointmentsPage } from './AppointmentsPage';
export { LoginPage } from './LoginPage';
export { TeamPage } from './TeamPage';
export { SettingsPage } from './SettingsPage';
export { SubscriptionPage } from './SubscriptionPage';
export { ProfilePage } from './ProfilePage';
export { CommandPage } from './CommandPage';
export { CashierPage } from './CashierPage';
export { ServicesPage } from './ServicesPage';
export { CommissionsPage } from './CommissionsPage';
export { AdminPage } from './AdminPage';
export { default as IntegrationsPage } from './IntegrationsPage';
export { default as AutomationPage } from './AutomationPage';
export { RecommendationRulesPage } from './RecommendationRulesPage';
export { RecommendationStatsPage } from './RecommendationStatsPage';
export { default as LoyaltySettingsPage } from './LoyaltySettingsPage';
export { default as LoyaltyDashboardPage } from './LoyaltyDashboardPage';
export { default as ProductSubscriptionPlansPage } from './ProductSubscriptionPlansPage';
export { default as SubscriptionDeliveriesPage } from './SubscriptionDeliveriesPage';
export { default as AvailableSubscriptionsPage } from './AvailableSubscriptionsPage';
export { default as UpsellRulesPage } from './UpsellRulesPage';
export { default as CartLinksPage } from './CartLinksPage';
export { default as CartLinkPublicPage } from './CartLinkPublicPage';
export { default as ReservationsPage } from './ReservationsPage';
export { default as ABTestsPage } from './ABTestsPage';
export { PaymentMethodsPage } from './PaymentMethodsPage';
export { PaymentDestinationsPage } from './PaymentDestinationsPage';
export { UsersManagementPage } from './UsersManagementPage';